#! /bin/sh
sxhkd &
#cd ~/HOME/ && python3 -m http.server &
~/.config/polybar/launch.sh &
#nitrogen --restore &
compton &

feh --bg-fill ~/Pictures/street_club_night_by_arsenixc_dbmfy60.jpg

bspc monitor -d 一 二 三 四 五 六 七 八

bspc config border_width         4
bspc config window_gap          38

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color \#4c566a
bspc config normal_border_color \#4c566a
bspc config focused_border_color \#d8dee9

bspc config top_padding 35
bspc config left_padding 30
bspc config right_padding 30
bspc config bottom_padding 3R0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
